server:
  port: 8762

spring:
  application:
    name: dcp-eureka-peer2

eureka:
  client:
    #  是否注册到eureka  
    register-with-eureka: false
    #  是否从eureka获取注册信息  
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/...