server:
  port: 8761

spring:
  application:
    name: dcp-eureka-peer1

eureka:
  client:
    #  是否注册到eureka
    register-with-eureka: false
    #  是否从eureka获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/...