#spring:
#  application:
#    name: config-client
#  config:
#    import: configserver:http://localhost:8888
#  profiles:
#    active: dev

logging:
  level:
    org: info

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
