spring:
  application:
    name: eureka-feign-client

  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        hc5:
          enabled: false
      http2client:
        enabled: false

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
